[package]
name = "simple_fbp"


[dependencies]
simple_actor = {path = "../simple_actor"}
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.86"
flume = "0.11.0"
rusty_pool = "0.7.0"
once_cell = "1.19.0"